/**
 * Route enums for the application
 */

export enum AppRoute {
  // Public pages
  HOME = 'HOME',
  CONTACT = 'CONTACT',
  BLOG = 'BLOG',
  BLOG_POST = 'BLOG_POST',

  // Auth pages
  AUTH_SIGNUP = 'AUTH_SIGNUP',
  AUTH_SIGNUP_VERIFY = 'AUTH_SIGNUP_VERIFY',
  AUTH_INVITE = 'AUTH_INVITE',
  AUTH_INVITE_VERIFY = 'AUTH_INVITE_VERIFY',
  AUTH_WELCOME_CREDENTIALS = 'AUTH_WELCOME_CREDENTIALS',
  AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET',

  // App pages (member area)
  APP_DASHBOARD = 'APP_DASHBOARD',
  APP_CALENDAR = 'APP_CALENDAR',
  APP_BLOG = 'APP_BLOG',
  APP_SETTINGS = 'APP_SETTINGS',
  APP_ANNIVERSARY_EVENT = 'APP_ANNIVERSARY_EVENT',
  APP_ANNIVERSARY_EVENT_NEW = 'APP_ANNIVERSARY_EVENT_NEW',
  APP_SLIDESHOW = 'APP_SLIDESHOW',

  // Admin pages
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_SITE_MEMBERS = 'ADMIN_SITE_MEMBERS',
  ADMIN_PENDING_MEMBERS = 'ADMIN_PENDING_MEMBERS',
  ADMIN_ANNIVERSARIES = 'ADMIN_ANNIVERSARIES',
}

/**
 * API route enum for centralized API URL generation
 * All routes except AUTH_* are site-scoped and require siteId
 */
export enum ApiRoute {
  // Auth routes (non-site-scoped)
  AUTH_ME = 'AUTH_ME',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REFRESH = 'AUTH_REFRESH',
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_SIGNUP_REQUEST_VERIFICATION = 'AUTH_SIGNUP_REQUEST_VERIFICATION',
  AUTH_SIGNUP_COMPLETE_VERIFICATION = 'AUTH_SIGNUP_COMPLETE_VERIFICATION',
  AUTH_SIGNUP_VERIFY = 'AUTH_SIGNUP_VERIFY',
  AUTH_ME_FIREBASE_TOKEN = 'AUTH_ME_FIREBASE_TOKEN',
  AUTH_INVITE_ME = 'AUTH_INVITE_ME',
  AUTH_INVITE_BY_TOKEN = 'AUTH_INVITE_BY_TOKEN',

  // General (non-site-scoped)
  SITE_PUBLIC_INFO = 'SITE_PUBLIC_INFO',
  ADMIN_CONTACT_MESSAGES = 'ADMIN_CONTACT_MESSAGES',
  USER_BLOG_ENABLE = 'USER_BLOG_ENABLE',
  USER_BLOG_REGISTER = 'USER_BLOG_REGISTER',

  // Site info
  SITE_INFO = 'SITE_INFO',
  SITE_DESCRIPTION = 'SITE_DESCRIPTION',
  SITE_SETTINGS = 'SITE_SETTINGS',

  // Pictures & Photos
  SITE_PICTURES = 'SITE_PICTURES',
  SITE_PHOTOS = 'SITE_PHOTOS',
  SITE_PHOTO_BY_ID = 'SITE_PHOTO_BY_ID',
  SITE_PHOTO_IMAGE_LIKES = 'SITE_PHOTO_IMAGE_LIKES',
  SITE_PICTURES_LIKES = 'SITE_PICTURES_LIKES',

  // Anniversaries & Calendar
  SITE_ANNIVERSARIES = 'SITE_ANNIVERSARIES',
  SITE_ANNIVERSARY_BY_ID = 'SITE_ANNIVERSARY_BY_ID',
  SITE_ANNIVERSARY_EVENT_BY_ID = 'SITE_ANNIVERSARY_EVENT_BY_ID',
  SITE_ANNIVERSARY_EVENT_IMAGE_LIKES = 'SITE_ANNIVERSARY_EVENT_IMAGE_LIKES',
  SITE_ANNIVERSARY_EVENTS = 'SITE_ANNIVERSARY_EVENTS',
  SITE_ANNIVERSARY_BLESSING_PAGES = 'SITE_ANNIVERSARY_BLESSING_PAGES',
  SITE_CALENDAR_OCCURRENCES = 'SITE_CALENDAR_OCCURRENCES',

  // Members
  SITE_MEMBER_INFO = 'SITE_MEMBER_INFO',
  SITE_MEMBERS = 'SITE_MEMBERS',
  SITE_MEMBERS_PUBLIC = 'SITE_MEMBERS_PUBLIC',
  SITE_MEMBERS_COUNT = 'SITE_MEMBERS_COUNT',
  SITE_MEMBER_BY_ID = 'SITE_MEMBER_BY_ID',
  SITE_MEMBERS_APPROVE = 'SITE_MEMBERS_APPROVE',
  SITE_MEMBERS_REJECT = 'SITE_MEMBERS_REJECT',
  SITE_PENDING_MEMBERS = 'SITE_PENDING_MEMBERS',
  SITE_PENDING_MEMBERS_APPROVE = 'SITE_PENDING_MEMBERS_APPROVE',
  SITE_PENDING_MEMBERS_REJECT = 'SITE_PENDING_MEMBERS_REJECT',
  SITE_INVITES = 'SITE_INVITES',

  // Profile
  SITE_PROFILE = 'SITE_PROFILE',
  SITE_PROFILE_AVATAR = 'SITE_PROFILE_AVATAR',

  // Blog
  SITE_BLOG = 'SITE_BLOG',
  SITE_BLOG_COUNT = 'SITE_BLOG_COUNT',
  SITE_BLOG_ENABLE = 'SITE_BLOG_ENABLE',
  SITE_BLOG_SLUG_CHECK = 'SITE_BLOG_SLUG_CHECK',
  SITE_BLOG_TRANSLATE = 'SITE_BLOG_TRANSLATE',
  SITE_BLOG_LIKE = 'SITE_BLOG_LIKE',
  SITE_BLOG_SHARE = 'SITE_BLOG_SHARE',

  // Blessing Pages
  SITE_BLESSING_PAGES_BY_SLUG = 'SITE_BLESSING_PAGES_BY_SLUG',
  SITE_BLESSING_PAGE_BLESSINGS = 'SITE_BLESSING_PAGE_BLESSINGS',
  SITE_BLESSING_BY_ID = 'SITE_BLESSING_BY_ID',

  // Admin
  SITE_ADMIN_CONTACT = 'SITE_ADMIN_CONTACT',
  SITE_ADMIN_CACHE_REVALIDATE = 'SITE_ADMIN_CACHE_REVALIDATE',
  SITE_ADMIN_USER_HARD_DELETE = 'SITE_ADMIN_USER_HARD_DELETE',
  SITE_ADMIN_OWNER = 'SITE_ADMIN_OWNER',

  // Dropbox
  SITE_DROPBOX_BROWSE = 'SITE_DROPBOX_BROWSE',
  SITE_DROPBOX_IMPORT = 'SITE_DROPBOX_IMPORT',

  // Contact
  SITE_CONTACT = 'SITE_CONTACT',
}

export interface UrlParams {
  locale?: string;
  token?: string;
  siteId?: string;
  id?: string;
  handle?: string;
  code?: string;
  [key: string]: string | undefined;
}
