#!/usr/bin/env tsx
/**
 * dasi#3 / famcircle#165 - build-stamped APP_VERSION, never hand-maintained.
 * Runs at the start of every build (and dev boot, via npm's predev/prebuild
 * lifecycle hooks - see package.json) to regenerate src/generated/version.ts
 * from the build clock + the current git commit. See
 * docs/fleet-versioning-standard.md. The generated file is gitignored -
 * nothing for a human to forget to bump. Reference implementation:
 * markette#198 (Markette's scripts/stamp-version.mts), adapted here to this
 * repo's own .ts/tsx convention rather than Markette's .mts.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

export function formatCalVer(d: Date): string {
  const yy = String(d.getFullYear() % 100);
  const m = String(d.getMonth() + 1);
  const dd = String(d.getDate()).padStart(2, '0');
  const hh = String(d.getHours()).padStart(2, '0');
  const mm = String(d.getMinutes()).padStart(2, '0');
  return `${yy}.${m}.${dd}-${hh}${mm}`;
}

function resolveCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim();
  } catch {
    // VERCEL_GIT_COMMIT_SHA is set on Vercel builds even in shallow-clone
    // setups where a local git call can fail.
    const sha = process.env.VERCEL_GIT_COMMIT_SHA;
    return sha ? sha.slice(0, 7) : 'unknown';
  }
}

function main() {
  const version = formatCalVer(new Date());
  const commit = resolveCommit();

  const here = fileURLToPath(new URL('.', import.meta.url));
  const outDir = join(here, '..', 'src', 'generated');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    join(outDir, 'version.ts'),
    `// Auto-generated by scripts/stamp-version.ts - do not edit, do not commit.\n` +
      `export const APP_VERSION = ${JSON.stringify(version)};\n` +
      `export const APP_COMMIT = ${JSON.stringify(commit)};\n`,
  );
  console.log(`[stamp-version] APP_VERSION=${version} APP_COMMIT=${commit}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
